#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK  GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS    GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK  GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN   GPIO_NUM_38
#define AUDIO_I2S_GPIO_DOUT  GPIO_NUM_48

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_21
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_47
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO        GPIO_NUM_1
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_18
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_17
#define AI_BUTTON_GPIO          GPIO_NUM_4

#define BATTERY_ADC_PIN         GPIO_NUM_3

#define EPD_SPI_NUM        SPI3_HOST

#define EPD_BUSY_PIN   GPIO_NUM_10
#define EPD_RST_PIN    GPIO_NUM_11
#define EPD_DC_PIN     GPIO_NUM_12
#define EPD_MOSI_PIN   GPIO_NUM_13
#define EPD_SCK_PIN    GPIO_NUM_14
#define EPD_CS_PIN     GPIO_NUM_15

#define EXAMPLE_LCD_WIDTH   400
#define EXAMPLE_LCD_HEIGHT  300
 
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#endif // _BOARD_CONFIG_H_